apiVersion: v1
kind: Pod
metadata:
  name: clr-shell-demo
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: clr-nginx
    image: bluewish/nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
